language: php
php:
    - "5.6"
    - "7.0"
    - "7.1"

# Allow to use container infrastructure
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
    - phpenv config-add travis.php.ini
    - phpenv config-rm xdebug.ini || echo "xdebug not available for PHP $TRAVIS_PHP_VERSION"
    - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then
        echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
      fi;
    - if [ "$TRAVIS_PHP_VERSION" = "7.0" ] || [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then
        pecl install mongodb;
      fi;
    - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then
        yes '' | pecl install apcu-4.0.11;
      fi;
    - if [ "$TRAVIS_PHP_VERSION" = "7.0" ] || [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then
        yes '' | pecl install apcu;
      fi;
    - npm install -g grunt-cli

install:
    - mysql -u root -e 'CREATE DATABASE akeneo_pim;'
    - mysql -u root -e 'CREATE USER "akeneo_pim"@"localhost" IDENTIFIED BY "akeneo_pim";'
    - mysql -u root -e 'GRANT ALL ON akeneo_pim.* TO "akeneo_pim"@"localhost";'
    - composer update --prefer-dist --no-interaction --ignore-platform-reqs
    - if [ "$TRAVIS_PHP_VERSION" = "7.0" ] || [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then
        composer require alcaeus/mongo-php-adapter --ignore-platform-reqs;
      fi;
    - ./app/console pim:install -e=test
    - ./app/console oro:requirejs:generate-config
    - npm install
    - curl http://get.sensiolabs.org/php-cs-fixer-v1.11.phar -o php-cs-fixer

before_script:
    - cp ./app/config/parameters.yml ./app/config/parameters_test.yml

script:
    - ./bin/phpunit -c app/phpunit.travis.xml --testsuite PIM_Unit_Test
    - ./bin/phpunit -c app/phpunit.travis.xml --testsuite PIM_Integration_Test
    - ./bin/phpspec run
    - php php-cs-fixer fix --dry-run -v --diff --config-file=.php_cs.php
    - grunt travis

notifications:
  slack: akeneo:fDZaQeRRj1gVtXCW3f2kQAxo

matrix:
  allow_failures:
    - php: "7.1"
